# ~/.config/alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "None"
startup_mode = "Windowed"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.0

[colors.primary]
background = "#262335"
foreground = "#f0eff1"

[colors.cursor]
text = "#f0eff1"
cursor = "#f92aad"

[colors.normal]
black = "#2b213c"
red = "#ff8080"
green = "#95ffa4"
yellow = "#ffe9aa"
blue = "#91ddff"
magenta = "#c991e1"
cyan = "#aaffe4"
white = "#cbe3e7"

[colors.bright]
black = "#565575"
red = "#ff5458"
green = "#62d196"
yellow = "#ffb378"
blue = "#65b2ff"
magenta = "#906cff"
cyan = "#63f2f1"
white = "#a6b3cc"

[colors.selection]
text = "#f0eff1"
background = "#ff8080"

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = "Block"
blink_interval = 750

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "F11", mods = "None", action = "ToggleFullscreen" },
    { key = "Paste", mods = "None", action = "Paste" },
    { key = "Copy", mods = "None", action = "Copy" },
    { key = "L", mods = "Control", action = "ClearLogNotice" },
    { key = "L", mods = "Control", chars = "\f" },
    { key = "PageUp", mods = "None", action = "ScrollPageUp" },
    { key = "PageDown", mods = "None", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", action = "ScrollToTop" },
    { key = "End", mods = "Shift", action = "ScrollToBottom" },
]
