# ============================================
# تنظیمات عمومی
# ============================================

# تنظیم فونت
font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: "Regular"
  size: 16.0

# تنظیم رنگ‌ها (تم Synthwave)
colors:
  primary:
    background: '#0F0C29'  # رنگ پس‌زمینه
    foreground: '#FFFFFF'  # رنگ متن
  normal:
    black:   '#1C1C1C'
    red:     '#FF6B6B'
    green:   '#6BCB77'
    yellow:  '#FFD93D'
    blue:    '#D77DD2'
    magenta: '#C23BEE'
    cyan:    '#69F0AE'
    white:   '#E0E0E0'
  bright:
    black:   '#414141'
    red:     '#FF6E6E'
    green:   '#B6E880'
    yellow:  '#FFE29E'
    blue:    '#89DDFF'
    magenta: '#C792EA'
    cyan:    '#A3F7FF'
    white:   '#FFFFFF'

# ============================================
# تنظیمات پنجره
# ============================================

# حاشیه‌های پنجره
window:
  padding:
    x: 10
    y: 10
  dynamic_padding: false
  decorations: full

# ============================================
# تنظیمات اسکرول
# ============================================

scrolling:
  history: 10000
  auto_save_on_scroll: false

# ============================================
# تنظیمات مشکل‌پذیری
# ============================================

selection:
  semantic_escape_chars: " `!@#$%^&*()-=+[{]}\\|;:'\",<.>/?"

# ============================================
# تنظیمات موس
# ============================================

mouse:
  double_click:
    threshold: 300
  triple_click:
    threshold: 300

# ============================================
# تنظیمات کپی و پیست
# ============================================

clipboard:
  # فعال‌سازی کلیپ‌بورد Wayland
  clipboard: true

# ============================================
# تنظیمات ویسول
# ============================================

# تعداد خطوط visible در ویسول
scrolling:
  history: 10000

# ============================================
# تنظیمات انیمیشن
# ============================================

# فعال کردن انیمیشن‌ها
enable_animations: true

# ============================================
# تنظیمات ترمینال
# ============================================

colors:
  cursor:
    text: '#FFFFFF'
    cursor: '#FF6EC7'
  selection:
    text: '#FFFFFF'
    background: '#A3F7FF'

# ============================================
# تنظیمات کاراکتر
# ============================================

char:
  unicode_version: "12.1"

# ============================================
# تنظیمات انترپرتر داخلی
# ============================================

shell:
  program: /bin/bash
  args:
    - --login

# ============================================
# پایان تنظیمات
# ============================================
